package com.brcolow.game;

public enum VkStructureType {
    VK_STRUCTURE_TYPE_APPLICATION_INFO,
    VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO,
    VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO,
    VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO,
    VK_STRUCTURE_TYPE_SUBMIT_INFO,
    VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO,
    VK_STRUCTURE_TYPE_MAPPED_MEMORY_RANGE,
    VK_STRUCTURE_TYPE_BIND_SPARSE_INFO,
    VK_STRUCTURE_TYPE_FENCE_CREATE_INFO,
    VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO,
    VK_STRUCTURE_TYPE_EVENT_CREATE_INFO,
    VK_STRUCTURE_TYPE_QUERY_POOL_CREATE_INFO,
    VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO,
    VK_STRUCTURE_TYPE_BUFFER_VIEW_CREATE_INFO,
    VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO,
    VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO,
    VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO,
    VK_STRUCTURE_TYPE_PIPELINE_CACHE_CREATE_INFO,
    VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,
    VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO,
    VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO,
    VK_STRUCTURE_TYPE_PIPELINE_TESSELLATION_STATE_CREATE_INFO,
    VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO,
    VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO,
    VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO,
    VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO,
    VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO,
    VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO,
    VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO,
    VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO,
    VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO,
    VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO,
    VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO,
    VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO,
    VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO,
    VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SE,
    VK_STRUCTURE_TYPE_COPY_DESCRIPTOR_SET,
    VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO,
    VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO,
    VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO,
    VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO,
    VK_STRUCTURE_TYPE_COMMAND_BUFFER_INHERITANCE_INFO,
    VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO,
    VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO,
    VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER,
    VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER,
    VK_STRUCTURE_TYPE_MEMORY_BARRIER,
    VK_STRUCTURE_TYPE_LOADER_INSTANCE_CREATE_INFO,
    VK_STRUCTURE_TYPE_LOADER_DEVICE_CREATE_INFO,
    // Provided by VK_EXT_debug_utils
    VK_STRUCTURE_TYPE_DEBUG_UTILS_OBJECT_NAME_INFO_EXT,
    // Provided by VK_EXT_debug_utils
    VK_STRUCTURE_TYPE_DEBUG_UTILS_OBJECT_TAG_INFO_EXT,
    // Provided by VK_EXT_debug_utils
    VK_STRUCTURE_TYPE_DEBUG_UTILS_LABEL_EXT,
    // Provided by VK_EXT_debug_utils
    VK_STRUCTURE_TYPE_DEBUG_UTILS_MESSENGER_CALLBACK_DATA_EXT,
    // Provided by VK_EXT_debug_utils
    VK_STRUCTURE_TYPE_DEBUG_UTILS_MESSENGER_CREATE_INFO_EXT,
    INTERNAL_UNKNOWN;

    public static VkStructureType VkStructureType(int structureType) {
        return switch (structureType) {
            case 0 -> VK_STRUCTURE_TYPE_APPLICATION_INFO;
            case 1 -> VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO;
            case 2 -> VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO;
            case 3 -> VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO;
            case 4 -> VK_STRUCTURE_TYPE_SUBMIT_INFO;
            case 5 -> VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
            case 6 -> VK_STRUCTURE_TYPE_MAPPED_MEMORY_RANGE;
            case 7 -> VK_STRUCTURE_TYPE_BIND_SPARSE_INFO;
            case 8 -> VK_STRUCTURE_TYPE_FENCE_CREATE_INFO;
            case 9 -> VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO;
            case 10 -> VK_STRUCTURE_TYPE_EVENT_CREATE_INFO;
            case 11 -> VK_STRUCTURE_TYPE_QUERY_POOL_CREATE_INFO;
            case 12 -> VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
            case 13 -> VK_STRUCTURE_TYPE_BUFFER_VIEW_CREATE_INFO;
            case 14 -> VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
            case 15 -> VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
            case 16 -> VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
            case 17 -> VK_STRUCTURE_TYPE_PIPELINE_CACHE_CREATE_INFO;
            case 18 -> VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
            case 19 -> VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO;
            case 20 -> VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO;
            case 21 -> VK_STRUCTURE_TYPE_PIPELINE_TESSELLATION_STATE_CREATE_INFO;
            case 1000128000 -> VK_STRUCTURE_TYPE_DEBUG_UTILS_OBJECT_NAME_INFO_EXT;
            case 1000128001 -> VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO;
            case 1000128002 -> VK_STRUCTURE_TYPE_DEBUG_UTILS_LABEL_EXT;
            case 1000128003 -> VK_STRUCTURE_TYPE_DEBUG_UTILS_MESSENGER_CALLBACK_DATA_EXT;
            case 1000128004 -> VK_STRUCTURE_TYPE_DEBUG_UTILS_MESSENGER_CREATE_INFO_EXT;
            default -> {
                System.out.println("Unhandled VkStructureType code: " + structureType);
                yield INTERNAL_UNKNOWN;
            }
        };
    }
}
